version: '3'
name: ocatave

services:
  lavalink:
    build:
      context: lavalink
    ports:
      - 2334:2334
    restart: unless-stopped
  bot:
    build:
      context: .
    environment:
      LAVALINK_HOST: "lavalink:2334"
      LAVALINK_PASSPHRASE: alpharius
    restart: unless-stopped
