FROM golang:1.18.3-bullseye

COPY . .

ENV GOPATH=""
ENV TOKEN=OTg0NDg2NzAwNjU3MDIxMDA4.GaDRmY.iJWedKov4U6TTf5UpN234WT7Y_ZiCMA6WWHfXU
ENV LAVALINK_HOST="lavalink_octave:2334"
ENV LAVALINK_PASSPHRASE=youshallnotpass

RUN go build

CMD ["./octave"]